#include "draw.h"
#include "gba.h"

#include <stdio.h>

#include "images/startPage.h"
#include "images/stageOne.h"
#include "images/stageTwo.h"

static void undrawDiver(AppState *state);
void drawAppState(AppState *state);
static void drawSharks(AppState *state);
static void drawDiver(AppState *state);
static void undrawSharks(AppState *state);

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    if (state->stage == FIRST_STAGE) {
		    drawFullScreenImageDMA((unsigned short *)stageOne);
    } else if (state->stage == SECOND_STAGE) {
		    drawFullScreenImageDMA((unsigned short *)stageTwo);
    }
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    undrawDiver(state);
    undrawSharks(state);
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    drawDiver(state);
    drawSharks(state);
    if (state->stage == FIRST_STAGE) {
      char *str = "Stage 1";
      drawString(4, 4, str, BLACK);
    } else if (state->stage == SECOND_STAGE) {
      char *str = "Stage 2";
      drawString(4, 4, str, BLACK);
    }
}

//Draw a Yellow square which represents a diver.
static void drawDiver(AppState *state) {
    Diver *diver = &(state->diver);
    drawRectDMA(diver->x, diver->y, diver->width, diver->width, diver->color);
}

//Draws a red square which represents a shark.
static void drawSharks(AppState *state) {
    Shark *sharks = state->shark;
    int numOfSharks = sizeof(sharks);

    for (int i = 0; i < numOfSharks; i++) {
	     int x = sharks[i].x;
	     int y = sharks[i].y;
       volatile u16 color = sharks[i].color;
	     int width = sharks[i].width;
	     drawRectDMA(x, y, width, width, color);
    }
}

//undraw the diver from the previous location.
static void undrawDiver(AppState *state) {
    Diver *diver = &(state->diver);
    int x = diver->x;
    int y = diver->y;
    int width = diver->width;
    if (state->stage == FIRST_STAGE) {
      drawRectDMA(x, y, width, width, BLUE);
    } else if (state->stage == SECOND_STAGE) {
    	drawRectDMA(x, y, width, width, BLUE);
    }
}

//undraw the shark from the previous location.
static void undrawSharks(AppState *state) {
    Shark *sharks = state->shark;
    int numOfSharks = sizeof(sharks);

    if (state->stage == FIRST_STAGE || state->stage == SECOND_STAGE) {
      for (int i = 0; i < numOfSharks; i++) {
         int width = sharks[i].width;
         drawRectDMA(sharks[i].x, sharks[i].y, width, width, BLUE);
      }
    }
}
