#include "gba.h"
#include "logic.h"
#include "draw.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include <stdio.h>
#include <stdlib.h>
#include "images/startPage.h"
#include "images/stageOne.h"
#include "images/stageTwo.h"
#include "images/gameover.h"
#include "images/clear.h"
void makeFirstStage(AppState *appState);
void makeSecondStage(AppState *appState);

// AppState enum definition
typedef enum {
        // TA-TODO: Add any additional states you need for your app.
        START,
        START_NODRAW,
        APP_INTRO,
        APP_INTRO_NODRAW,
        APP_INIT_FIRST_STAGE,
        APP_FIRST_STAGE,
        APP_INIT_SECOND_STAGE,
        APP_SECOND_STAGE,
        APP_GAMEOVER,
        APP_GAME_CLEAR,
        APP_EXIT_NODRAW
} GBAState;

int main(void) {
        // TA-TODO: Manipulate REG_DISPCNT here to set Mode 3.
        REG_DISPCNT = MODE3 | BG2_ENABLE;

        GBAState state = START;

        // We store the "previous" and "current" states.
        AppState currentAppState, nextAppState;

        // We store the current and previous values of the button input.
        u32 previousButtons = BUTTONS;
        u32 currentButtons = BUTTONS;

        while(1) {
                // Load the current state of the buttons
                currentButtons = BUTTONS;

                // TA-TODO: Manipulate the state machine below as needed.
                switch(state) {
                case START:
                        // Wait for VBlank
                        waitForVBlank();

                        // TA-TODO: Draw the start state here : Done
                        drawFullScreenImageDMA((unsigned short *) startPage);
                        state = START_NODRAW;
                        break;
                case START_NODRAW:
                        // TA-TODO: Check for a button press here to start the app.
                        // Start the app by switching the state to APP_INIT.

                        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                                state = APP_INTRO;
                                previousButtons = previousButtons | BUTTON_START;
                        }
                        break;

                case APP_INTRO:
                        //show intro Page.
                        fillScreenDMA(BLUE);
                        char *str = "* Your Goal: get the treasure box!";
                        drawString(6, 15, str, WHITE);
                        str = "You can move by pressing arrow keys";
                        drawString(9, 32, str, WHITE);
                        drawRectDMA(80, 60, 6, 6, YELLOW);
                        str = "* A diver,(  ) that's you!.";
                        drawString(10, 60, str, WHITE);
                        drawRectDMA(80, 78, 6, 6, RED);

                        str = "* A shark (  ) DON'T be eaten by it.";
                        drawString(10, 78, str, WHITE);

                        str = "Press SELECT button to return";
                        drawString(20, 105, str, WHITE);
                        str = " to the start screen";
                        drawString(55, 117, str, WHITE);

                        str = "PRESS START TO GET THE TREASURE!";
                        drawString(20, 140, str, WHITE);

                        state = APP_INTRO_NODRAW;

                        break;
                case APP_INTRO_NODRAW:
                        /**
                           Start the game if START button is pressed and
                           the game returns to the start page if SELECT button is pressed.
                         */
                        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                                state = APP_INIT_FIRST_STAGE;
                                previousButtons = previousButtons | BUTTON_START;
                        }
                        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                                state = START;
                                previousButtons = previousButtons | BUTTON_SELECT;
                        }
                        break;
                case APP_INIT_FIRST_STAGE:

                        // Initialize the app.
                        initializeAppState(&currentAppState);
                        makeFirstStage(&currentAppState);

                        // Draw the initial state of the app
                        fullDrawAppState(&currentAppState);
                        state = APP_FIRST_STAGE;

                        break;
                case APP_FIRST_STAGE:

                        // Process the app for one frame, store the next state
                        nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);

                        // Wait for VBlank before we do any drawing.
                        waitForVBlank();

                        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                                state = START;
                                previousButtons = previousButtons | BUTTON_SELECT;
                        }

                        // Undraw the previous state
                        undrawAppState(&currentAppState);

                        // Draw the current state
                        drawAppState(&nextAppState);

                        // Now set the current state as the next state for the next iter.
                        currentAppState = nextAppState;

                        // Check if the app is exiting. If it is, then go to the exit state.
                        if (currentAppState.gameOver)  {
                                state = APP_GAMEOVER;
                        }
                        //Check if the diver reached the goal. If yes go to the next stage.
                        if (currentAppState.cntGoal) {
                                state = APP_INIT_SECOND_STAGE;
                        }
                        break;
                case APP_INIT_SECOND_STAGE:
                        // Initialize the app.
                        initializeAppState(&currentAppState);
                        makeSecondStage(&currentAppState);

                        // draw initial state of the app.
                        state = APP_SECOND_STAGE;
                        fullDrawAppState(&currentAppState);
                        break;
                case APP_SECOND_STAGE:

                        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                                state = START;
                                previousButtons = previousButtons | BUTTON_SELECT;
                        }
                        // Process the app for one frame, store the next state
                        nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);

                        // Wait for VBlank before we do any drawing.
                        waitForVBlank();

                        // Undraw the previous state
                        undrawAppState(&currentAppState);

                        // Draw the current state
                        drawAppState(&nextAppState);

                        // Now set the current state as the next state for the next iter.
                        currentAppState = nextAppState;

                        // Check if the app is exiting. If it is, then go to the exit state.
                        if (currentAppState.gameOver) state = APP_GAMEOVER;
                        //Check if the player has reached the goal. If it has, then go to the exit state.
                        if (currentAppState.cntGoal) state = APP_GAME_CLEAR;
                        break;
                case APP_GAMEOVER:
                        // Wait for VBlank
                        waitForVBlank();

                        // TA-TODO: Draw the exit / gameover screen

                        drawFullScreenImageDMA((unsigned short *)gameover);
                        state = APP_EXIT_NODRAW;
                        break;
                case APP_GAME_CLEAR:

                        //Draw clear page when user won the game.
                        waitForVBlank();

                        drawFullScreenImageDMA((unsigned short *)clear);

                        state = APP_EXIT_NODRAW;
                        break;
                case APP_EXIT_NODRAW:
                        // TA-TODO: Check for a button press here to go back to the start screen

                        if (KEY_DOWN(BUTTON_START, BUTTONS)) state = START;
                        break;
                }

                // Store the current state of the buttons
                previousButtons = currentButtons;
        }

        return 0;
}
